name: Ejecucion de python
run-name: ${{ github.actor }} esta corriendo un archivo de python
on: [push]
jobs:
  ejecuta-script-python:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Iniciando actions"
        - run: python --version
        - run: Check out repository code
        - run: actions/checkout@v6
        - run: ls -als
        - run: python app.py