name: Expression 
on:  
  workflow_dispatch: 
    inputs:
      edad: 
        description: 'Edad'
        required: true 
        type: number 
      nombre: 
        description: 'Tu nombre' 
        required: true 
        default: 'Juan' 
        type: string 
jobs:
    mayor:
      if: ${{ inputs.edad >= 18 }}
      runs-on: ubuntu-latest
      steps:
          - name: corriendo script
            run: echo "${{ inputs.nombre }} es mayor de edad"
    menor:
      if: ${{ inputs.edad < 18 }}
      runs-on: ubuntu-latest
      steps:
          - name: corriendo script
            run: echo "${{ inputs.nombre }} es menor de edad"
    ejecuta-python-condicionales:
      runs-on: ubuntu-latest
      steps:
        - run: echo "EDAD=${{ inputs.edad }}" >> $GITHUB_ENV 
        - run: echo "NOMBRE=${{ inputs.nombre }}" >> $GITHUB_ENV
        - uses: actions/checkout@v6
        - run: python condicionales.py 
        