name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world wuuuuu"
      - run: echo "Escribo en un archivo" > file.txt
      - run: ls -al
      - run: cat file.txt
      - run: rm -rf file.txt
      - run: ls -al
