name: Ejecucion de JS
run-name: ${{ github.actor }} esta corriendo un archivo de Js
on: [push]
jobs:
  ejecuta-script-JavaScript:
    runs-on: ubuntu-latest
    steps:
        - run: echo "Iniciando actions"
        - run: node --version
        - name: Check out repository code
          uses: actions/checkout@v6
        - run: ls -al
        - run: node app.js
  ejecuta-script-JavaScript-deno:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Iniciando actions de Deno"
            - name: Config Deno
              uses: denoland/setup-deno@v2
            - run: Deno --version
            - name: Check out repository code
              uses: actions/checkout@v6
            - run: ls -al
            - run: deno app.js