name: Ejecucion de 3 triggers
run-name: ${{ github.actor }} esta ejecutando 3 triggers
on:
    push:
        branches:
            - 'main'
            - 'develop'
    issues:
        types: [opened, edited, closed]
    
    schedule:
        - cron: '30 5,17 * * *'


jobs:
    ejecucion-tres-triggers:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Ejecucion de triggers"
            - run: echo "Hola mundo"
